# Generated by Django 5.0.6 on 2024-06-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_updates_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/'),
        ),
    ]
