# Generated by Django 5.0.6 on 2024-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_updates_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
