# Generated by Django 5.0.6 on 2024-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_image_article_image_url_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
