# Generated by Django 5.0.6 on 2024-05-26 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_remove_articles_author_delete_updates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish'], name='blog_articl_publish_2a54df_idx'),
        ),
    ]
