# Generated by Django 5.0.6 on 2024-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_author_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveIndex(
            model_name='updates',
            name='blog_update_publish_bf73ab_idx',
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='publish',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='updates',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddIndex(
            model_name='updates',
            index=models.Index(fields=['-published'], name='blog_update_publish_9088a5_idx'),
        ),
    ]
